title: DJ Gill
description: A portfolio site
url: https://itsmed.github.io/
author: Dejon Gill
twitter:
  username: dejongill
logo: assets/images/cyndi.jpg
social:
  name: Dejon Gill
  links:
    - https://twitter.com/dejongill
    - https://linkedin.com/in/dejongill
    - https://github.com/itsmed
